# Site settings
title: Aleksandr Mezin
email: mezin.alexander@gmail.com
baseurl: ""
url: "https://amezin.github.io/"
github_username: amezin
linkedin_profile: alexandermezin
disqus_shortname: amezin

# Build settings
markdown: kramdown
